### ISSUE TITLE
SFTP transfer does not work with Ruby 2.0

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/sshkit#528]
When I try to enable functional tests in our CI matrix (#522), I see that the new SFTP implementation added in #524 fails on Ruby 2.0:

> NoMethodError: undefined method `size' for #<Net::SFTP::Operations::File:0x007fcb8982f648>

**Comment by mattbrictson** [comment]
I believe this is because modern versions of net-* do not support older Rubies, so Bundler resolves to net-sftp v2.1.2, which does not have the `File#size` method. We should be able to use this instead: `file.stat.size`.
